include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore