name: jenkins_board
description: Jenkins desktop.
publish_to: 'none' 

version: 0.5.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.1
  go_router: ^5.2.1
  state_notifier: ^0.7.2
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  url_launcher: ^6.1.7
  line_icons: ^2.0.1
  fluttertoast: ^8.1.1
  equatable: ^2.0.3
  intl: ^0.17.0
  google_fonts: ^3.0.1
  local_notifier: ^0.1.5
  reorderables: ^0.5.1
  popover: ^0.2.7
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  custom_pop_up_menu: ^1.2.4

dev_dependencies:
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/