name: Flutter Cross Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.2.0
        with:
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y tar clang cmake ninja-build pkg-config libgtk-3-dev make libwebkit2gtk-4.0-dev keybinder-3.0 python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build linux
      - run: make deb
      - run: make tar
      - run: wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
      - run: chmod +x /usr/local/bin/appimagetool
      - run: pip3 install appimage-builder
      - run: make appimage
      - uses: actions/upload-artifact@v2
        with:
          name: Jenkins-Board-Linux-Bundle
          path: |
            build/jenkins-board-linux-x86_64.deb
            build/jenkins-board-linux-x86_64.tar.xz
            build/jenkins-board-linux-x86_64.AppImage
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.2.0
        with:
          cache: true
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: choco install make -y
      - run: make innoinstall
      - run: make inno
      - run: make choco
      - uses: actions/upload-artifact@v2
        with:
          name: Jenkins-Board-Windows-Bundle
          path: |
            build/installer/jenkins-board-windows-x86_64-setup.exe
            build/jenkins-board.*.nupkg
  build_macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - run: du -sh build/macos/Build/Products/Release/Jenkins\ Board.app
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MAC0S_CERTIFICATE_PWD
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          echo "Create Keychain"
          security create-keychain -p 123456 build.keychain
          echo "Assign to Login Keychain"
          security default-keychain -s build.keychain
          echo "Unlock the Login Keychain"
          security unlock-keychain -p 123456 build.keychain
          echo "Import certificate"
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          echo "Set Key Partition"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k 123456 build.keychain
          echo "Find Identity"
          security find-identity
          echo "Sign the app"
          /usr/bin/codesign --force --deep -s 9FU28TNNLS build/macos/Build/Products/Release/Jenkins\ Board.app
      - run: npm install -g appdmg
      - run: appdmg appdmg.json build/jenkins-board-macos-x86_64.dmg
      - uses: actions/upload-artifact@v2
        with:
          name: Jenkins-Board-Macos-Bundle
          path: |
            build/macos/Build/Products/Release/Jenkins Board.app
            build/jenkins-board-macos-x86_64.dmg